image:
  repository: cauldyclark15/mongodb-backup
  tag: latest
  pullPolicy: IfNotPresent

mongodb:
  uri: "your-mongodb-uri"
  oplog: "true"

linode:
  bucketName: "your-bucket-name"
  cliToken: "your-linode-cli-token"

backup:
  password: ""

schedule: "0 */1 * * *"

secrets:
  mongodbUriSecretName: mongodb-uri
  linodeSecretName: linode
  backupSecretName: backup-secrets
