apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-mongodb
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  suspend: false
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: backup-mongodb
              image: cauldyclark15/mongodb-backup:d2a541afefdf1630e154d828250557841a6aa795
              env:
                - name: MONGODB_URI
                  valueFrom:
                    secretKeyRef:
                      name: mongodb-uri
                      key: MONGODB_URI

                - name: MONGODB_OPLOG
                  value: "true"

                - name: BUCKET_NAME
                  valueFrom:
                    secretKeyRef:
                      name: linode
                      key: BUCKET_NAME

                - name: LINODE_CLI_OBJ_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: linode
                      key: LINODE_CLI_OBJ_ACCESS_KEY

                - name: LINODE_CLI_OBJ_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: linode
                      key: LINODE_CLI_OBJ_SECRET_KEY

                - name: LINODE_CLI_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: linode
                      key: LINODE_CLI_TOKEN

                - name: REGION
                  valueFrom:
                    secretKeyRef:
                      name: linode
                      key: REGION

                - name: DATABASE
                  value: {{ .Values.database }}
