name: Docker Image CI

on:
  push:
    branches:
      - release
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_CNC_USERNAME }}
          password: ${{ secrets.DOCKERHUB_CNC_TOKEN }}
      - name: Docker Build and Push
        run: |
          docker build --tag ${{ secrets.DOCKERHUB_CNC_USERNAME }}/${{ secrets.DOCKERHUB_MONGODB_BACKUP_REPOSITORY }}:${{ github.sha }} .
          docker push ${{ secrets.DOCKERHUB_CNC_USERNAME }}/${{ secrets.DOCKERHUB_MONGODB_BACKUP_REPOSITORY }}:${{ github.sha }}
